### ISSUE TITLE
Need help to understand one struct

### ISSUE THREAD

**Issue by tejaskumark** [MalcolmJSmith/WiFiMon#1]
Hi Malcolm,

I stumbled across your repo, and it helped me a lot to understand wlanapi using into golang. I must say it has been quite old but yet relavent to current date. Thanks for that.
I am reaching out to you for one of my query, I am trying to use winapi - https://docs.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlansetprofileeapxmluserdata, and I am quite a bit lost here. 
As per description - 
- strProfileName
The name of the profile associated with the EAP user data. Profile names are case-sensitive. This string must be NULL-terminated.

- strEapXmlUserData
A pointer to XML data used to set the user credentials.

Both of above having same type LPCWSTR, but one is direct string and another one is pointer. So I am not sure how to translate these two types to golang struct.
If you can help me with this or give me an example, that woule be great.

**Comment by tejaskumark** [comment]
@MalcolmJSmith

**Comment by MalcolmJSmith** [comment]
Hello Tejaskumar

I think the winapi documentation is confusing, and both parameters are pointers to a string.

You can use this to get a pointer to a NULL-terminated string:
`p, err := syscall.UTF16PtrFromString("Test")`

and then convert to a uintptr:
`uintptr(unsafe.Pointer(p))`

Best Regards
Malcolm

**Comment by tejaskumark** [comment]
Hi Malcolm,
Thanks a lot, for clarifying my doubt.
